In [1]:
print("NutriClass Project Started")

NutriClass Project Started

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries Loaded")

Libraries Loaded

In [4]:
df = pd.read_excel("../data/food_dataset.csv.xlsx")
df.head()

,Calories,Protein,Fat,Carbs,Sugar,Fiber,Sodium,Cholesterol,Glycemic_Index,Water_Content,Serving_Size,Meal_Type,Preparation_Method,Is_Vegan,Is_Gluten_Free,Food_Name
0,290.463673,14.340084,14.152608,35.266644,4.828030,1.291432,647.553389,24.990309,81.575896,45.669118,197.570043,dinner,fried,False,False,Pizza
1,212.626748,4.080908,11.621584,23.218957,16.347814,0.130303,68.572414,34.301652,69.522492,49.854415,103.833510,snack,raw,False,True,Ice Cream
2,330.695408,14.326708,19.747680,29.479164,6.251137,0.794477,663.171859,34.816834,62.552384,40.132866,198.989367,snack,raw,False,False,Burger
3,198.070798,9.452445,5.475896,32.097878,2.984621,1.710468,300.749543,28.510998,68.688853,57.423461,135.714202,lunch,fried,False,True,Sushi
4,274.496228,6.099547,16.256002,29.756638,17.352958,1.465676,296.314958,15.403173,70.385059,33.170460,73.019474,snack,baked,False,False,Donut

In [5]:
df.isnull().sum()

Calories              375
Protein               375
Fat                   375
Carbs                 375
Sugar                 375
Fiber                 375
Sodium                375
Cholesterol           375
Glycemic_Index        375
Water_Content         375
Serving_Size          375
Meal_Type               0
Preparation_Method      0
Is_Vegan                0
Is_Gluten_Free          0
Food_Name               0
dtype: int64

In [8]:
df.fillna(df.select_dtypes(include="number").mean(), inplace=True)

,Calories,Protein,Fat,Carbs,Sugar,Fiber,Sodium,Cholesterol,Glycemic_Index,Water_Content,Serving_Size,Meal_Type,Preparation_Method,Is_Vegan,Is_Gluten_Free,Food_Name
0,290.463673,14.340084,14.152608,35.266644,4.828030,1.291432,647.553389,24.990309,81.575896,45.669118,197.570043,dinner,fried,False,False,Pizza
1,212.626748,4.080908,11.621584,23.218957,16.347814,0.130303,68.572414,34.301652,69.522492,49.854415,103.833510,snack,raw,False,True,Ice Cream
2,330.695408,14.326708,19.747680,29.479164,6.251137,0.794477,663.171859,34.816834,62.552384,40.132866,198.989367,snack,raw,False,False,Burger
3,198.070798,9.452445,5.475896,32.097878,2.984621,1.710468,300.749543,28.510998,68.688853,57.423461,135.714202,lunch,fried,False,True,Sushi
4,274.496228,6.099547,16.256002,29.756638,17.352958,1.465676,296.314958,15.403173,70.385059,33.170460,73.019474,snack,baked,False,False,Donut
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31695,103.937793,1.251053,0.452045,27.891970,14.836599,1.835365,2.326263,0.000000,53.690101,81.784216,120.293342,lunch,fried,True,True,Banana
31696,246.063812,10.269973,13.106895,36.416636,5.684908,1.571570,600.167326,20.839330,81.153823,41.760973,192.062481,lunch,raw,False,False,Pizza
31697,299.997105,12.431992,11.512833,33.808189,5.737315,2.901049,586.095363,28.956145,75.144055,37.981317,197.318164,breakfast,grilled,False,False,Pizza
31698,352.146284,9.170255,8.340631,39.261887,1.731604,0.027763,20.681808,7.559997,73.299415,48.435802,152.072098,dinner,grilled,False,False,Pasta
31699,203.952826,5.322650,13.419346,26.686660,14.645211,0.295026,62.468736,38.417093,57.987511,51.156165,113.912626,breakfast,grilled,False,True,Ice Cream

In [9]:
df.isnull().sum()

Calories              0
Protein               0
Fat                   0
Carbs                 0
Sugar                 0
Fiber                 0
Sodium                0
Cholesterol           0
Glycemic_Index        0
Water_Content         0
Serving_Size          0
Meal_Type             0
Preparation_Method    0
Is_Vegan              0
Is_Gluten_Free        0
Food_Name             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(313)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 31387 entries, 0 to 31699
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Calories            31387 non-null  float64
 1   Protein             31387 non-null  float64
 2   Fat                 31387 non-null  float64
 3   Carbs               31387 non-null  float64
 4   Sugar               31387 non-null  float64
 5   Fiber               31387 non-null  float64
 6   Sodium              31387 non-null  float64
 7   Cholesterol         31387 non-null  float64
 8   Glycemic_Index      31387 non-null  float64
 9   Water_Content       31387 non-null  float64
 10  Serving_Size        31387 non-null  float64
 11  Meal_Type           31387 non-null  str
 12  Preparation_Method  31387 non-null  str
 13  Is_Vegan            31387 non-null  bool
 14  Is_Gluten_Free      31387 non-null  bool
 15  Food_Name           31387 non-null  str
dtypes: bool(2), float64(11), str(3)
memory usage: 3.7 MB

In [14]:
df["Food_Name"].nunique()

10

In [15]:
from sklearn.preprocessing import LabelEncoder

le_food = LabelEncoder()
df["Food_Name"] = le_food.fit_transform(df["Food_Name"])

le_meal = LabelEncoder()
df["Meal_Type"] = le_meal.fit_transform(df["Meal_Type"])

le_prep = LabelEncoder()
df["Preparation_Method"] = le_prep.fit_transform(df["Preparation_Method"])

In [16]:
X = df.drop("Food_Name", axis=1)
y = df["Food_Name"]

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [20]:
y_pred = rf_model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9912392481682064

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99       311
           1       0.99      0.99      0.99       222
           2       0.98      0.99      0.98       969
           3       1.00      1.00      1.00       929
           4       0.99      0.99      0.99       606
           5       0.99      1.00      0.99       825
           6       0.99      0.99      0.99      1153
           7       0.99      0.99      0.99       199
           8       0.99      0.99      0.99       393
           9       0.99      0.99      0.99       671

    accuracy                           0.99      6278
   macro avg       0.99      0.99      0.99      6278
weighted avg       0.99      0.99      0.99      6278

In [22]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

Logistic Regression Accuracy: 0.9912392481682064

In [23]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))

KNN Accuracy: 0.9890092386110226

In [24]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))

Decision Tree Accuracy: 0.9858235106721885

In [25]:
model_scores = {
    "Random Forest": accuracy_score(y_test, y_pred),
    "Logistic Regression": accuracy_score(y_test, lr_pred),
    "KNN": accuracy_score(y_test, knn_pred),
    "Decision Tree": accuracy_score(y_test, dt_pred)
}

pd.DataFrame.from_dict(model_scores, orient="index", columns=["Accuracy"])

                     Accuracy
Random Forest        0.991239
Logistic Regression  0.991239
KNN                  0.989009
Decision Tree        0.985824

In [26]:
import joblib

joblib.dump(rf_model, "../models/nutriclass_model.pkl")
joblib.dump(scaler, "../models/scaler.pkl")
joblib.dump(le_food, "../models/food_encoder.pkl")

['../models/food_encoder.pkl']

In [27]:
model = joblib.load("../models/nutriclass_model.pkl")
scaler = joblib.load("../models/scaler.pkl")
encoder = joblib.load("../models/food_encoder.pkl")

sample_input = X_test[0].reshape(1, -1)
pred = model.predict(sample_input)

print("Predicted Food:", encoder.inverse_transform(pred))

Predicted Food: ['Donut']

In [ ]:
#Random Forest achieved the highest accuracy of 99.12%. The model effectively learns relationships between nutritional attributes and food identity. The system can reliably predict exact food items for given nutritional profiles, enabling strict diet planning.